<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Aspire.StackExchange.Redis"/>
    <PackageReference Include="CommunityToolkit.Aspire.MassTransit.RabbitMQ"/>
    <PackageReference Include="MassTransit.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TixTapGo.Shared\TixTapGo.Shared.csproj"/>
  </ItemGroup>
</Project>
