<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\TixTapGo.Shared\TixTapGo.Shared.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TixTapGo.VenueService"/>
    <InternalsVisibleTo Include="TixTapGo.VenueService.Worker"/>
  </ItemGroup>
</Project>
